/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Category {
  created_at: Generated<Timestamp | null>;
  description: string | null;
  icon: string | null;
  id: Generated<number>;
  name: string;
  sort: Generated<number | null>;
  updated_at: Generated<Timestamp | null>;
  user_id: number | null;
}

export interface User {
  avatar_url: string | null;
  created_at: Generated<Timestamp | null>;
  email: string;
  id: Generated<number>;
  password: string;
  updated_at: Generated<Timestamp | null>;
  username: string;
}

export interface DB {
  category: Category;
  user: User;
}
